# Generated by Django 4.0.5 on 2022-06-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='bookcoverimage',
            field=models.ImageField(blank=True, null=True, upload_to='coverimage/'),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='bookdescription',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
