# Generated by Django 4.0.5 on 2022-06-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel_app', '0002_alter_addbook_bookcoverimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='bookpdf',
            field=models.ImageField(blank=True, null=True, upload_to='contentpdf/'),
        ),
    ]
